# 1. 基本的なサーバー (Port 8080)
server {
    listen 8080;
    server_name localhost;
    root ./docs;
    index index.html;

    # GETメソッドのテスト ./docs/get/index.htmlをgetする
    # curl -v http://localhost:8080/get/index.html
    location /get {
        allow_methods GET;
    }

    # POSTとアップロードのテスト ./docs/upload/
    # upload_storeがあるときは、upload_store + リクエストURIの最後のファイル名　./docs/uploads + index.html
    # ないときは、root + URIのパスになる ./docs + /upload/指定したファイル名
    # curl -v -d "Hello, Webserv!" http://localhost:8080/upload/test.txt
    location /upload {
        allow_methods POST;
        client_max_body_size 1000000000;
        upload_store ./docs/uploads;
    }

    # DELETEのテスト POSTでuploadしたファイルを消す ./docs/uploads/test.txtを消去
    location /uploads {
        allow_methods DELETE;
        index test.txt;
    }

    # Autoindexのテスト
    # curl -v http://localhost:8080/images/
    location /images {
        allow_methods GET;
        autoindex on;
    }
}

# 2. リダイレクト専用サーバー (Port 8081)
# curl -v http://localhost:8081/ responseの中身
# curl -v -L http://localhost:8081/ リダイレクト先まで追従して表示する
server {
    listen 8081;
    server_name localhost;

    location / {
        return 301 http://google.com;
    }
}

# 3. デフォルトエラーページのテスト (Port 8082)
#　もしリソースが見つからなかったらエラーページを探す処理に入りパスを取得しようとする
# error_pageディレクトリからパスを取得して、探してroot + そのパスになる
# curl -v http://localhost:8082/is_this_not_found ファイルがないので404エラーでリダイレクトされるか
# curl -v -X POST http://localhost:8082/ POSTメソッドを送ったときに405エラーでリダイレクトされるか
server {
    listen 8082;
    root ./docs;
    server_name localhost;
    error_page 400 errors/400.html;
    error_page 403 errors/403.html;
    error_page 404 errors/404.html;
    error_page 405 errors//405.html;
    error_page 413 errors//413.html;
    error_page 414 errors//414.html;
    error_page 431 errors//431.html;
    error_page 500 errors//500.html;
    error_page 501 errors//501.html;
    error_page 505 errors//505.html;

    location /get {
        allow_methods GET;
        index forbid.txt;
    }

    location /get/index.html {
        client_max_body_size 5;
    }
}

  # kBadRequest = 400,　 リクエストのURIの部分でスペースがあったり、最初が'/'で始まってない　HTTPで始まっているか
                        # echo -e "GET /path with space HTTP/1.1\r\nHost: localhost:8082\r\n\r\n" | nc localhost 8082
                        # echo -e "GET hoge HTTP/1.1\r\nHost: localhost:8082\r\n\r\n" | nc localhost 8082
  # kForbidden = 403,　権限をなくす  chmod 000 ./docs/get/forbid.txt  curl http://localhost:8082/get/
  # kNotFound = 404,　みつからない # curl -v http://localhost:8082/is_this_not_found
  # kMethodNotAllowed = 405,　メソッドが許可されてない curl -v -X POST http://localhost:8082/get
  # kContentTooLarge = 413,　　bodyの許可を小さくしておく curl -v -d "Hello World" http://localhost:8082/get/index.html
  # kUriTooLong = 414,　　　　　非常に長いURI　curl -v "http://localhost:8082/$(python3 -c 'print("a"*2048)')"
  # kRequestHeaderFieldsTooLarge = 431, # 1万文字以上の巨大なカスタムヘッダーを送りつける
                                        # echo -e "GET / HTTP/1.1\r\nHost: localhost:8082\r\nLarge-Header: $(python3 -c 'print("a"*10000)')\r\n\r\n" | nc localhost 8082
  # kInternalServerError = 500, CGIスクリプトを途中でクラッシュさせる
  # kNotImplemented = 501, 実装していない未知のメソッドを送る curl -v -X METHOD http://localhost:8082/
  # kVersionNotSupported = 505,　echo -e "GET / HTTP/2.0\r\nHost: localhost:8082\r\n\r\n" | nc localhost 8082
