# 1.正常系テスト用（ポート 8080）
server {
    listen 8080;
    server_name localhost;
    root ./docs;
    # aaa
    index index.html;

    location /get {
       allow_methods GET; 
        index get.html;
    }
}

# server {
#     listen 8080;
#     server_name localhost;
#     root ./docs;
#     index index.html;

#     location /get {
#        allow_methods GET;
#         index get.html;
#     }
# }

