server {
    listen 8080;
    root ./;
    server_name cgi.test;
    error_page 404 docs/errors/404.html;
    error_page 500 docs/errors/500.html;
    error_page 502 docs/errors/502.html;
    error_page 504 docs/errors/504.html;

    location /get/ {
        allow_methods GET;
        root ./docs;
        index get.html;
    }

    location /cgi-bin/ {
        allow_methods GET POST;
        root .;
        cgi_handler .pl /usr/bin/perl;
        cgi_handler .py /usr/bin/python3;
        cgi_handler .php /usr/bin/php-cgi;
        cgi_handler .rb /usr/bin/ruby;
        cgi_handler .sh /bin/sh;
    }
}